// Tang Nano 9K: NANO QUEST, a small NES-style platformer on the HDMI port.
//
// Hold S2 to run right, press S1 to jump (hold it to jump higher). Bump ? blocks for
// coins (some hold a mushroom that makes Nano big: a hit then only shrinks Nano back),
// smash bricks from below, grab floating coins, stomp slimes, don't fall down the pits,
// and reach the flag before the time runs out. 100 coins give an extra life.
//
// The picture is 320x240 (each pixel 2x2 on screen) built from 16x16 tiles, 16x16
// sprites and an 8x8 font, all generated by platformer_gen.py. The game runs once per
// frame, reading the level map for collisions one tile per clock.
// LEDs show lives; a piezo between pin 25 and GND plays the sound effects.
module top (
    input  wire       clk,          // 27 MHz oscillator
    input  wire [1:0] btn,          // S1 jump, S2 run; active low
    output wire       tmds_clk_p,
    output wire       tmds_clk_n,
    output wire [2:0] tmds_d_p,
    output wire [2:0] tmds_d_n,
    output wire [5:0] led,          // active low
    output wire       beep
);
    wire        clk_pix, reset, frame;
    wire [9:0]  x, y;
    wire [23:0] rgb;

    dvi_tx #(.PIPE(3)) video (
        .clk_27(clk), .clk_pix(clk_pix), .reset(reset), .x(x), .y(y), .frame(frame),
        .rgb(rgb),
        .tmds_clk_p(tmds_clk_p), .tmds_clk_n(tmds_clk_n), .tmds_d_p(tmds_d_p), .tmds_d_n(tmds_d_n)
    );

    reg [1:0] btn_s1 = 2'b00, btn_s2 = 2'b00;
    always @(posedge clk_pix) begin
        btn_s1 <= ~btn;
        btn_s2 <= btn_s1;
    end

    wire [11:0]  ma_addr, mb_addr;
    wire [5:0]   ma_rd, mb_rd, mb_wd;
    wire         mb_we, reload;
    wire [2:0]   mode;
    wire [3:0]   sfx;
    wire [11:0]  cam_x, hero_x, timer;
    wire signed [9:0] hero_y;
    wire [3:0]   hero_f, lives, world;
    wire         hero_vis, hero_big;
    wire [26:0]  mush;
    wire [9:0]   mush_clip;
    wire [107:0] foes, debris;
    wire [26:0]  pop;
    wire [23:0]  score;
    wire [7:0]   coins, frames;

    plat_map level (
        .clk(clk_pix), .a_addr(ma_addr), .a_rd(ma_rd),
        .b_addr(mb_addr), .b_we(mb_we), .b_wd(mb_wd), .b_rd(mb_rd), .reload(reload)
    );

    plat_game game (
        .clk(clk_pix), .tick(frame), .btn_jump(btn_s2[0]), .btn_run(btn_s2[1]),
        .map_addr(mb_addr), .map_we(mb_we), .map_wd(mb_wd), .map_rd(mb_rd), .map_reload(reload),
        .mode(mode), .cam_x(cam_x), .hero_x(hero_x), .hero_y(hero_y), .hero_f(hero_f), .hero_vis(hero_vis),
        .hero_big(hero_big), .foes(foes), .pop(pop), .debris(debris), .mush(mush), .mush_clip(mush_clip),
        .score(score), .coins(coins), .timer(timer), .lives(lives), .world(world), .frames(frames), .sfx(sfx)
    );

    plat_render render (
        .clk(clk_pix), .x(x), .y(y), .mode(mode), .cam_x(cam_x),
        .hero_x(hero_x), .hero_y(hero_y), .hero_f(hero_f), .hero_vis(hero_vis), .hero_big(hero_big),
        .foes(foes), .pop(pop), .debris(debris), .mush(mush), .mush_clip(mush_clip),
        .score(score), .coins(coins), .timer(timer), .lives(lives), .world(world), .frames(frames),
        .map_addr(ma_addr), .map_rd(ma_rd), .rgb(rgb)
    );

    plat_sfx sound (.clk(clk_pix), .tick(frame), .sfx(sfx), .out(beep));

    assign led = ~{3'b000, lives >= 4'd3, lives >= 4'd2, lives >= 4'd1};
endmodule


// The level: 16 rows x 256 columns of tile ids. Port A is the renderer's, port B the game's.
// A reload pulse copies the pristine level back over the next 4096 clocks.
module plat_map (
    input  wire        clk,
    input  wire [11:0] a_addr,
    output reg  [5:0]  a_rd = 6'd0,
    input  wire [11:0] b_addr,
    input  wire        b_we,
    input  wire [5:0]  b_wd,
    output reg  [5:0]  b_rd = 6'd0,
    input  wire        reload
);
    reg [5:0] ram [0:4095];
    reg [5:0] rom [0:4095];
    initial begin
        $readmemh("plat_level.hex", ram);
        $readmemh("plat_level.hex", rom);
    end

    reg [12:0] cnt = 13'h1000;                          // copy position; bit 12 set when idle
    reg [5:0]  rom_q = 6'd0;
    reg [11:0] cp_addr = 12'd0;
    reg        cp_valid = 1'b0;

    always @(posedge clk) begin
        rom_q    <= rom[cnt[11:0]];
        cp_addr  <= cnt[11:0];
        cp_valid <= !cnt[12];
        if (reload)       cnt <= 13'd0;
        else if (!cnt[12]) cnt <= cnt + 1'b1;
    end

    wire [11:0] pb_addr = cp_valid ? cp_addr : b_addr;
    always @(posedge clk) begin
        if (cp_valid || b_we)
            ram[pb_addr] <= cp_valid ? rom_q : b_wd;
        b_rd <= ram[pb_addr];
    end

    always @(posedge clk)
        a_rd <= ram[a_addr];
endmodule


// Game state, advanced once per frame. The work after each tick is a sequence of steps,
// one per clock, because collision checks read the level map one tile at a time.
module plat_game (
    input  wire         clk,
    input  wire         tick,               // once per frame, in vertical blanking
    input  wire         btn_jump,
    input  wire         btn_run,
    output reg  [11:0]  map_addr = 12'd0,
    output reg          map_we = 1'b0,
    output reg  [5:0]   map_wd = 6'd0,
    input  wire [5:0]   map_rd,             // map[map_addr] two clocks after map_addr is set
    output reg          map_reload = 1'b0,
    output reg  [2:0]   mode = 3'd0,
    output reg  [11:0]  cam_x = 12'd0,
    output reg  [11:0]  hero_x = 12'd38,     // sprite position (the hitbox starts 2 px in)
    output reg  signed [9:0] hero_y = 10'sd192,
    output reg  [3:0]   hero_f = 4'd0,      // pose (F_STAND .. F_DEAD)
    output reg          hero_vis = 1'b1,
    output reg          hero_big = 1'b0,    // draw the 16x32 big Nano
    output reg  [107:0] foes = 108'd0,      // 4 slots of {vis, frame, y, x}
    output reg  [26:0]  pop = 27'd0,        // the coin popping out of a ? block
    output reg  [107:0] debris = 108'd0,    // 4 chunks of a broken brick, like foes
    output reg  [26:0]  mush = 27'd0,       // the mushroom, like foes
    output reg  [9:0]   mush_clip = 10'h3FF, // mushroom rows from here down are hidden (inside its block)
    output reg  [23:0]  score = 24'd0,      // 6 BCD digits
    output reg  [7:0]   coins = 8'd0,       // 2 BCD digits
    output reg  [11:0]  timer = 12'h300,    // 3 BCD digits
    output reg  [3:0]   lives = 4'd3,
    output reg  [3:0]   world = 4'd1,
    output reg  [7:0]   frames = 8'd0,
    output reg  [3:0]   sfx = 4'd0          // one-clock pulse: SFX_*
);
    `include "plat_params.vh"

    localparam [2:0] M_TITLE = 0, M_CARD = 1, M_PLAY = 2, M_DYING = 3, M_CLEAR = 4, M_GAMEOVER = 5, M_TIMEUP = 6;
    localparam [3:0] SFX_JUMP = 1, SFX_COIN = 2, SFX_STOMP = 3, SFX_BUMP = 4, SFX_DIE = 5, SFX_CLEAR = 6, SFX_1UP = 7,
                     SFX_BREAK = 8, SFX_SPROUT = 9, SFX_POWER = 10, SFX_SHRINK = 11;

    // Motion in 1/16 px and 1/16 px per frame.
    localparam [6:0]        ACC = 2, DEC = 4, VMAX = 36;
    localparam signed [8:0] JUMP_V = 84, STOMP_V = 60, GRAV = 8, GRAV_HOLD = 3, VY_MAX = 96;
    localparam [15:0]       FOE_V = 8;
    localparam [11:0]       CAM_LEAD = 144, CAM_MAX = 4096 - 320;
    localparam [15:0]       START_X = 40 * 16;
    localparam signed [15:0] START_Y = 192 * 16;

    // Hero (hitbox 12 wide at px, py; 16 tall, or 28 when big)
    reg        [15:0] px = START_X;
    reg signed [15:0] py = START_Y;
    reg        [6:0]  vx = 0;
    reg signed [8:0]  vy = 0;
    reg               on_ground = 1'b1, jump_prev = 1'b0, any_prev = 1'b1;
    reg        [7:0]  run_acc = 0;
    reg        [8:0]  mode_t = 0;               // frames spent in the current mode
    reg        [4:0]  tsub = 0;                 // frames per clock tick of the timer
    reg               fell = 1'b0;              // died in a pit (no hop)
    reg               big = 1'b0;               // grown by a mushroom
    reg        [5:0]  grow_t = 0;               // growing: the game pauses while Nano flickers
    reg        [7:0]  inv_t = 0;                // after shrinking: can't be hurt, flickers
    wire signed [11:0] hh = big ? 12'sd28 : 12'sd16;    // hitbox height

    // The mushroom: 0 none, 1 rising out of its block, 2 sliding along
    reg        [1:0]  mu_st = 0;
    reg        [15:0] mu_x = 0;
    reg signed [15:0] mu_y = 0;
    reg signed [7:0]  mu_vy = 0;
    reg               mu_left = 1'b0;
    reg        [4:0]  mu_t = 0;

    // Foes: 4 slots
    reg [63:0] fx = 0;                          // 16 bits each, 1/16 px
    reg [63:0] fy = 0;
    reg [31:0] fvy = 0;                         // 8 bits each
    reg [3:0]  fdir = 4'hF;                     // 1 = walking left
    reg [7:0]  fst = 0;                         // 2 bits each: 0 free, 1 walking, 2 squashed
    reg [23:0] ftm = 0;                         // 6 bits each
    reg [4:0]  spawn_ptr = 0;
    reg [11:0] spawn_rom [0:31];                // {column, row}
    initial $readmemh("plat_spawns.hex", spawn_rom);

    // Chunks of a broken brick: 1/16 px and 1/16 px per frame, like the hero
    reg [63:0] deb_x = 0, deb_y = 0;            // 16 bits each (y signed)
    reg [31:0] deb_vx = 0, deb_vy = 0;          // 8 bits each, signed
    reg [3:0]  deb_on = 0;
    reg signed [15:0] dyn;
    reg signed [11:0] dyp;

    // Coin popping out of a block
    reg        pop_on = 1'b0;
    reg [4:0]  pop_t = 0;
    reg [11:0] pop_x = 0;
    reg [9:0]  pop_y0 = 0;

    // ---------------------------------------------------------------- helpers
    function solid(input [5:0] t);
        solid = t[5];
    endfunction

    // Map address of the tile under pixel (xp, yp); anything above or below the screen is sky (row 15).
    function [11:0] tile_at(input [11:0] xp, input signed [11:0] yp);
        tile_at = (yp < 0 || yp > 239) ? {4'd15, xp[11:4]} : {yp[7:4], xp[11:4]};
    endfunction

    function [23:0] bcd_add(input [23:0] a, input [23:0] b);
        integer i;
        reg [4:0] d;
        reg       c;
        begin
            c = 1'b0;
            for (i = 0; i < 6; i = i + 1) begin
                d = a[4 * i +: 4] + b[4 * i +: 4] + c;
                c = d > 9;
                bcd_add[4 * i +: 4] = c ? d - 10 : d[3:0];
            end
        end
    endfunction

    function [11:0] bcd_dec3(input [11:0] a);
        integer i;
        reg     b;
        begin
            b = 1'b1;
            for (i = 0; i < 3; i = i + 1) begin
                if (b && a[4 * i +: 4] == 0) begin
                    bcd_dec3[4 * i +: 4] = 4'd9;
                end else begin
                    bcd_dec3[4 * i +: 4] = a[4 * i +: 4] - b;
                    b = 1'b0;
                end
            end
        end
    endfunction

    // ---------------------------------------------------------------- per-frame step machine
    reg  [5:0]  step = 0;
    reg  [1:0]  k = 0;                          // foe being processed
    reg  [5:0]  t1 = 0, t2r = 0;                // tiles from earlier probes
    reg  [15:0] nx = 0;
    reg signed [15:0] ny = 0;
    reg         bump = 1'b0, jump_edge = 1'b0, start = 1'b0;
    reg  [15:0] cfx;                            // current foe, unpacked
    reg signed [15:0] cfy;
    reg signed [7:0]  cfvy;

    reg  [11:0] nxp, xr, hx, fxp, hdx;
    reg signed [11:0] nyp, pyp, hy, fyp, hdy, feet;
    reg  [5:0]  t2;
    reg  [6:0]  vx_n;
    reg signed [8:0] vy_n;
    reg  [4:0]  free_k;
    reg  [11:0] sp;
    integer     i;

    task add_score(input [23:0] v);
        score <= bcd_add(score, v);
    endtask

    always @(posedge clk) begin
        sfx        <= 4'd0;
        map_we     <= 1'b0;
        map_reload <= 1'b0;

        case (step)
            // ---------------------------------------------------- tick: inputs and mode changes
            6'd0: if (tick) begin
                frames    <= frames + 1'b1;
                mode_t    <= mode_t + 1'b1;
                jump_edge = btn_jump && !jump_prev;
                start     = (btn_jump || btn_run) && !any_prev;
                jump_prev <= btn_jump;
                any_prev  <= btn_jump || btn_run;

                case (mode)
                    M_TITLE: begin
                        cam_x    <= 12'd0;
                        hero_x   <= START_X[15:4] - 12'd2;
                        hero_y   <= START_Y[13:4];
                        hero_f   <= F_STAND;
                        hero_vis <= 1'b1;
                        hero_big <= 1'b0;
                        foes     <= 108'd0;
                        pop      <= 27'd0;
                        debris   <= 108'd0;
                        mush     <= 27'd0;
                        if (mode_t == 9'd1) map_reload <= 1'b1;
                        if (start) begin
                            score <= 24'd0; coins <= 8'd0; lives <= 4'd3; world <= 4'd1;
                            mode <= M_CARD; mode_t <= 9'd0;
                        end
                    end

                    M_CARD: begin
                        // Black screen with the world and lives; reset the level meanwhile.
                        if (mode_t == 9'd0) map_reload <= 1'b1;
                        px <= START_X; py <= START_Y; vx <= 7'd0; vy <= 9'sd0; on_ground <= 1'b1;
                        cam_x <= 12'd0; spawn_ptr <= 5'd0; fst <= 8'd0; pop_on <= 1'b0;
                        timer <= 12'h300; tsub <= 5'd0; fell <= 1'b0;
                        hero_x <= 12'd128; hero_y <= 10'sd116; hero_f <= F_STAND; hero_vis <= 1'b1;
                        foes <= 108'd0; pop <= 27'd0; debris <= 108'd0; deb_on <= 4'd0;
                        big <= 1'b0; hero_big <= 1'b0; grow_t <= 6'd0; inv_t <= 8'd0;
                        mu_st <= 2'd0; mush <= 27'd0;
                        if (mode_t == 9'd150) begin
                            mode <= M_PLAY; mode_t <= 9'd0;
                        end
                    end

                    M_PLAY: if (grow_t != 0) begin
                        // Growing: everything waits while Nano flickers between small and big.
                        grow_t   <= grow_t - 1'b1;
                        pyp      = py >>> 4;
                        hero_big <= grow_t == 6'd1 || grow_t[2];
                        hero_y   <= (grow_t == 6'd1 || grow_t[2]) ? pyp - 12'sd4 : pyp + 12'sd12;
                    end else begin
                        // Run and jump.
                        vx_n = btn_run ? (vx + ACC > VMAX ? VMAX : vx + ACC) : (vx > DEC ? vx - DEC : 7'd0);
                        vy_n = vy;
                        if (on_ground && jump_edge) begin
                            vy_n = -JUMP_V;
                            sfx <= SFX_JUMP;
                        end
                        vy_n = vy_n + ((btn_jump && vy_n < 0) ? GRAV_HOLD : GRAV);
                        if (vy_n > VY_MAX) vy_n = VY_MAX;
                        vx <= vx_n;
                        vy <= vy_n;
                        nx  = px + vx_n;
                        nxp = nx[15:4];
                        pyp = py >>> 4;
                        xr  = nxp + 12'd11;
                        map_addr <= tile_at(xr, pyp + 12'sd1);       // right side, near the head
                        step <= 6'd1;
                    end

                    M_DYING: begin
                        // Freeze, hop up, fall off the screen; then lose a life.
                        hero_f <= F_DEAD;
                        hero_big <= 1'b0;
                        hero_vis <= 1'b1;
                        if (mode_t == 9'd20 && !fell) vy <= -9'sd64;
                        if ((mode_t > 9'd20 || fell) && py < 16'sd4800) begin      // until 300 px down
                            vy <= (vy + GRAV > VY_MAX) ? VY_MAX : vy + GRAV;
                            py <= py + vy;
                            hero_y <= (py + vy) >>> 4;
                        end
                        if (mode_t == 9'd160) begin
                            lives  <= lives - 1'b1;
                            mode   <= lives == 4'd1 ? M_GAMEOVER : M_CARD;
                            mode_t <= 9'd0;
                        end
                    end

                    M_TIMEUP: begin
                        hero_f <= F_DEAD;
                        hero_big <= 1'b0;
                        if (mode_t == 9'd150) begin
                            lives  <= lives - 1'b1;
                            mode   <= lives == 4'd1 ? M_GAMEOVER : M_CARD;
                            mode_t <= 9'd0;
                        end
                    end

                    M_CLEAR: begin
                        // Slide down the pole, walk into the castle, turn the time into points.
                        pyp = py >>> 4;
                        if (pyp < 12'sd192 - hh && px[15:4] < FLAG_X) begin
                            py <= py + 16'sd32;                         // slide down the pole
                            hero_f <= F_STAND;
                        end else if (px[15:4] < 12'd3264) begin
                            px <= px + 16'd16;                          // walk to the castle door
                            if (px[15:4] >= FLAG_X + 12'd8 && pyp < 12'sd208 - hh)
                                py <= py + 16'sd64;                     // hop down off the block
                            run_acc <= run_acc + 8'd16;
                            hero_f <= run_acc[7:6] == 2'd3 ? F_RUN2 : F_RUN1 + run_acc[7:6];
                        end else begin
                            hero_vis <= 1'b0;
                            if (timer != 12'h000) begin
                                timer <= bcd_dec3(timer);
                                add_score(24'h000050);
                                if (frames[2:0] == 3'd0) sfx <= SFX_BUMP;
                            end else if (mode_t > 9'd400) begin
                                world <= world == 4'd9 ? 4'd9 : world + 1'b1;
                                mode <= M_CARD; mode_t <= 9'd0;
                            end
                        end
                        hero_x <= px[15:4] - 12'd2;
                        hero_y <= big ? (py >>> 4) - 12'sd4 : py >>> 4;
                        hero_big <= big;
                        foes <= 108'd0;
                        debris <= 108'd0;
                        mush <= 27'd0;
                    end

                    default: begin      // M_GAMEOVER
                        hero_vis <= 1'b0;
                        foes <= 108'd0;
                        debris <= 108'd0;
                        if (mode_t == 9'd240) begin
                            mode <= M_TITLE; mode_t <= 9'd0;
                        end
                    end
                endcase
            end

            // ---------------------------------------------------- hero: walls ahead
            6'd1: begin
                map_addr <= tile_at(xr, pyp + hh - 12'sd2);         // right side, near the feet
                step <= 6'd2;
            end
            6'd2: begin
                t1 <= map_rd;
                map_addr <= tile_at(xr, pyp + 12'sd14);             // right side, the middle (big Nano)
                step <= 6'd3;
            end
            6'd3: begin
                t2r  <= map_rd;
                step <= 6'd4;
            end
            6'd4: begin
                t2 = map_rd;
                if (vx != 0 && (solid(t1) || solid(t2r) || solid(t2))) begin
                    nxp = {xr[11:4], 4'd0} - 12'd12;                // stop against the wall
                    nx  = {nxp, 4'd0};
                    vx  <= 7'd0;
                end
                // Floor or ceiling, depending on direction.
                ny  = py + vy;
                nyp = ny >>> 4;
                map_addr <= tile_at(nxp + 12'd1, vy < 0 ? nyp : nyp + hh);        // head, or just below the feet
                step <= 6'd5;
            end
            6'd5: begin
                map_addr <= tile_at(nxp + 12'd10, vy < 0 ? nyp : nyp + hh);
                step <= 6'd6;
            end
            6'd6: begin
                t1 <= map_rd;
                step <= 6'd7;
            end
            6'd7: begin
                t2 = map_rd;
                bump = 1'b0;
                if (vy >= 0) begin
                    if (solid(t1) || solid(t2)) begin
                        feet = nyp + hh;                                // stand on top of that tile
                        nyp  = {feet[11:4], 4'd0} - hh;
                        ny   = {nyp, 4'd0};
                        vy  <= 9'sd0;
                        on_ground <= 1'b1;
                    end else begin
                        on_ground <= 1'b0;
                    end
                end else begin
                    on_ground <= 1'b0;                              // rising: in the air
                    if (solid(t1) || solid(t2)) begin
                        bump = 1'b1;
                        nyp = {nyp[11:4] + 8'd1, 4'd0};             // just below the block
                        ny  = {nyp, 4'd0};
                        vy  <= 9'sd8;
                    end
                end
                map_addr <= tile_at(nxp + 12'd6, (ny >>> 4) - 12'sd1);   // the block above the head
                step <= bump ? 6'd8 : 6'd10;
            end
            6'd8: step <= 6'd9;
            6'd9: begin
                // Bumped a block: ? blocks give a coin (or a mushroom) and become used; bricks break.
                if (map_rd == T_QBLOCK_M) begin
                    map_we   <= 1'b1;
                    map_wd   <= T_USED;
                    mu_st    <= 2'd1;                               // rise out of the block
                    mu_t     <= 5'd0;
                    mu_x     <= {map_addr[7:0], 8'd0};
                    mu_y     <= {map_addr[11:8], 8'd0};
                    mu_vy    <= 8'sd0;
                    mu_left  <= 1'b0;
                    mush_clip <= {2'b00, map_addr[11:8], 4'd0};
                    sfx      <= SFX_SPROUT;
                end else if (map_rd == T_QBLOCK) begin
                    map_we   <= 1'b1;
                    map_wd   <= T_USED;
                    pop_on   <= 1'b1;
                    pop_t    <= 5'd0;
                    pop_x    <= {map_addr[7:0], 4'd0};
                    pop_y0   <= {map_addr[11:8], 4'd0} - 10'd16;
                    coins    <= coins == 8'h99 ? 8'h00 : (coins[3:0] == 4'd9 ? {coins[7:4] + 4'd1, 4'd0} : coins + 8'd1);
                    if (coins == 8'h99) begin lives <= lives + 1'b1; sfx <= SFX_1UP; end
                    else sfx <= SFX_COIN;
                    add_score(24'h000200);
                end else if (map_rd == T_BRICK) begin
                    // Smash it: the brick goes and four chunks fly out of its corners.
                    map_we <= 1'b1;
                    map_wd <= T_SKY;
                    deb_on <= 4'hF;
                    for (i = 0; i < 4; i = i + 1) begin
                        deb_x[16 * i +: 16]  <= {map_addr[7:0], 8'd0} + (i % 2 == 1 ? 16'd128 : 16'd0);
                        deb_y[16 * i +: 16]  <= {map_addr[11:8], 8'd0} + (i >= 2 ? 16'd128 : 16'd0);
                        deb_vx[8 * i +: 8]   <= i % 2 == 1 ? 8'sd20 : -8'sd20;
                        deb_vy[8 * i +: 8]   <= i >= 2 ? -8'sd40 : -8'sd72;
                    end
                    add_score(24'h000050);
                    sfx <= SFX_BREAK;
                end else if (solid(map_rd)) begin
                    sfx <= SFX_BUMP;
                end
                step <= 6'd10;
            end

            // ---------------------------------------------------- hero: coins
            6'd10: begin
                map_addr <= tile_at(nxp + 12'd6, (ny >>> 4) + 12'sd4);
                step <= 6'd11;
            end
            6'd11: step <= 6'd12;
            6'd12: begin
                if (map_rd == T_COIN) begin
                    map_we <= 1'b1;
                    map_wd <= T_SKY;
                    coins  <= coins == 8'h99 ? 8'h00 : (coins[3:0] == 4'd9 ? {coins[7:4] + 4'd1, 4'd0} : coins + 8'd1);
                    if (coins == 8'h99) begin lives <= lives + 1'b1; sfx <= SFX_1UP; end
                    else sfx <= SFX_COIN;
                    add_score(24'h000200);
                end
                step <= 6'd13;
            end
            6'd13: begin
                map_addr <= tile_at(nxp + 12'd6, (ny >>> 4) + hh - 12'sd4);
                step <= 6'd14;
            end
            6'd14: step <= 6'd15;
            6'd15: begin
                if (map_rd == T_COIN) begin
                    map_we <= 1'b1;
                    map_wd <= T_SKY;
                    coins  <= coins == 8'h99 ? 8'h00 : (coins[3:0] == 4'd9 ? {coins[7:4] + 4'd1, 4'd0} : coins + 8'd1);
                    if (coins == 8'h99) begin lives <= lives + 1'b1; sfx <= SFX_1UP; end
                    else sfx <= SFX_COIN;
                    add_score(24'h000200);
                end
                step <= 6'd16;
            end

            // ---------------------------------------------------- hero: commit, camera, time, spawns
            6'd16: begin
                px <= nx;
                py <= ny;
                nyp = ny >>> 4;
                if (nyp > 12'sd240) begin                       // fell down a pit
                    mode <= M_DYING; mode_t <= 9'd0; fell <= 1'b1; sfx <= SFX_DIE;
                end else if (nxp + 12'd11 >= FLAG_X) begin      // reached the flag
                    mode <= M_CLEAR; mode_t <= 9'd0; sfx <= SFX_CLEAR;
                    px <= {FLAG_X - 12'd12, 4'd0};
                    vx <= 7'd0;
                end
                if (nxp > cam_x + CAM_LEAD)
                    cam_x <= (nxp - CAM_LEAD > CAM_MAX) ? CAM_MAX : nxp - CAM_LEAD;

                // Hero sprite (big Nano's is 32 tall, 4 px above the hitbox). After being hit it
                // flickers while it can't be hurt.
                if (!on_ground)     hero_f <= F_JUMP;
                else if (vx == 0)   hero_f <= F_STAND;
                else                hero_f <= run_acc[7:6] == 2'd3 ? F_RUN2 : F_RUN1 + run_acc[7:6];
                run_acc  <= vx == 0 ? 8'd0 : run_acc + vx;
                hero_x   <= nxp - 12'd2;
                hero_y   <= big ? nyp - 12'sd4 : nyp;
                hero_big <= big;
                hero_vis <= inv_t == 0 || frames[1];
                if (inv_t != 0) inv_t <= inv_t - 1'b1;

                // The clock.
                if (tsub == 5'd23) begin
                    tsub  <= 5'd0;
                    timer <= bcd_dec3(timer);
                    if (timer == 12'h001) begin mode <= M_TIMEUP; mode_t <= 9'd0; sfx <= SFX_DIE; end
                end else begin
                    tsub <= tsub + 1'b1;
                end

                // Coin pop animation: up 2 px a frame, then down, then gone.
                if (pop_on) begin
                    pop_t <= pop_t + 1'b1;
                    if (pop_t == 5'd20) pop_on <= 1'b0;
                end
                pop <= {pop_on, F_COIN0 + {2'b00, pop_t[2:1]}, pop_y0 - (pop_t < 12 ? {4'd0, pop_t, 1'b0} : 10'd24 - {5'd0, pop_t - 5'd12}),
                        pop_x};

                // Brick chunks fly and fall until they drop off the screen.
                for (i = 0; i < 4; i = i + 1) begin
                    dyn = $signed(deb_y[16 * i +: 16]) + $signed(deb_vy[8 * i +: 8]);
                    dyp = dyn >>> 4;
                    if (deb_on[i]) begin
                        deb_x[16 * i +: 16] <= deb_x[16 * i +: 16] + {{8{deb_vx[8 * i + 7]}}, deb_vx[8 * i +: 8]};
                        deb_y[16 * i +: 16] <= dyn;
                        // Cap the fall speed: past +127 the 8-bit speed would wrap and fling
                        // the chunk back up.
                        deb_vy[8 * i +: 8]  <= $signed(deb_vy[8 * i +: 8]) > 8'sd90 ? 8'sd96
                                                                            : $signed(deb_vy[8 * i +: 8]) + 8'sd6;
                        if (dyp > 12'sd240) deb_on[i] <= 1'b0;
                    end
                    debris[27 * i +: 27] <= {deb_on[i], F_DEBRIS, dyp[9:0], deb_x[16 * i + 4 +: 12]};
                end

                // Bring in the next foe once its column is about to scroll into view.
                sp = spawn_rom[spawn_ptr];
                free_k = fst[1:0] == 0 ? 5'd0 : fst[3:2] == 0 ? 5'd1 : fst[5:4] == 0 ? 5'd2 : fst[7:6] == 0 ? 5'd3 : 5'd4;
                if (spawn_ptr < SPAWNS && {sp[11:4], 4'd0} < cam_x + 12'd336 && free_k < 5'd4) begin
                    fx[16 * free_k +: 16]  <= {sp[11:4], 8'd0};
                    fy[16 * free_k +: 16]  <= {sp[3:0], 8'd0};
                    fvy[8 * free_k +: 8]   <= 8'd0;
                    fdir[free_k]           <= 1'b1;
                    fst[2 * free_k +: 2]   <= 2'd1;
                    spawn_ptr <= spawn_ptr + 1'b1;
                end
                k    <= 2'd0;
                step <= 6'd17;
            end

            // ---------------------------------------------------- foes, one at a time
            6'd17: begin
                cfx  = fx[16 * k +: 16];
                cfy  = fy[16 * k +: 16];
                cfvy = fvy[8 * k +: 8];
                if (fst[2 * k +: 2] == 2'd1) begin
                    cfvy = (cfvy + 8'sd8 > 8'sd96) ? 8'sd96 : cfvy + 8'sd8;
                    cfx  = fdir[k] ? cfx - FOE_V : cfx + FOE_V;
                    cfy  = cfy + cfvy;
                end
                fxp = cfx[15:4];
                fyp = cfy >>> 4;
                map_addr <= tile_at(fdir[k] ? fxp : fxp + 12'd15, fyp + 12'sd8);     // wall ahead
                step <= 6'd18;
            end
            6'd18: begin
                map_addr <= tile_at(fxp + 12'd2, fyp + 12'sd16);                     // floor, left
                step <= 6'd19;
            end
            6'd19: begin
                t1 <= map_rd;
                map_addr <= tile_at(fxp + 12'd13, fyp + 12'sd16);                    // floor, right
                step <= 6'd20;
            end
            6'd20: begin
                t2 = map_rd;
                step <= 6'd21;
                if (fst[2 * k +: 2] == 2'd1 && solid(t1)) begin                      // bumped a wall: turn
                    fdir[k] <= !fdir[k];
                    cfx = fdir[k] ? cfx + FOE_V : cfx - FOE_V;
                end
                t1 <= t2;
            end
            6'd21: begin
                // t1 = floor left, map_rd = floor right
                if (fst[2 * k +: 2] == 2'd1 && cfvy >= 0 && (solid(t1) || solid(map_rd))) begin
                    feet = fyp + 12'sd16;
                    fyp  = {feet[11:4], 4'd0} - 12'sd16;
                    cfy  = {fyp, 4'd0};
                    cfvy = 8'sd0;
                end
                fxp = cfx[15:4];
                fyp = cfy >>> 4;
                hx  = px[15:4];
                hy  = py >>> 4;
                case (fst[2 * k +: 2])
                    2'd1: begin
                        if (fyp > 12'sd240 || fxp + 12'd32 < cam_x) begin
                            fst[2 * k +: 2] <= 2'd0;                                 // gone
                        end else if (mode == M_PLAY && hx + 12'd11 > fxp + 12'd1 && hx < fxp + 12'd15 &&
                                     hy + hh - 12'sd1 > fyp + 12'sd5 && hy < fyp + 12'sd16) begin
                            if (vy > 0 && hy + hh - 12'sd1 < fyp + 12'sd13) begin    // stomped
                                fst[2 * k +: 2] <= 2'd2;
                                ftm[6 * k +: 6] <= 6'd30;
                                vy <= -STOMP_V;
                                add_score(24'h000100);
                                sfx <= SFX_STOMP;
                            end else if (inv_t != 0) begin
                                // just shrank: pass through
                            end else if (big) begin                                  // ouch: shrink
                                big   <= 1'b0;
                                py    <= py + 16'sd192;                              // keep the feet in place
                                inv_t <= 8'd120;
                                sfx   <= SFX_SHRINK;
                            end else begin                                           // ouch
                                mode <= M_DYING; mode_t <= 9'd0; sfx <= SFX_DIE;
                            end
                        end
                    end
                    2'd2: begin
                        ftm[6 * k +: 6] <= ftm[6 * k +: 6] - 1'b1;
                        if (ftm[6 * k +: 6] == 6'd1) fst[2 * k +: 2] <= 2'd0;
                    end
                    default: ;
                endcase
                fx[16 * k +: 16] <= cfx;
                fy[16 * k +: 16] <= cfy;
                fvy[8 * k +: 8]  <= cfvy;
                foes[27 * k +: 27] <= {fst[2 * k +: 2] != 2'd0,
                                       fst[2 * k +: 2] == 2'd2 ? F_SLIME_FLAT : (frames[3] ? F_SLIME1 : F_SLIME2),
                                       fyp[9:0], fxp};
                k    <= k + 1'b1;
                step <= k == 2'd3 ? 6'd22 : 6'd17;
            end

            // ---------------------------------------------------- the mushroom
            6'd22: begin
                if (mu_st == 2'd1) begin
                    mu_y <= mu_y - 16'sd16;                         // rise 1 px a frame
                    mu_t <= mu_t + 1'b1;
                    if (mu_t == 5'd15) begin mu_st <= 2'd2; mush_clip <= 10'h3FF; end
                    step <= 6'd27;
                end else begin
                    cfx  = mu_x;
                    cfy  = mu_y;
                    cfvy = (mu_vy + 8'sd8 > 8'sd96) ? 8'sd96 : mu_vy + 8'sd8;
                    if (mu_st == 2'd2) begin
                        cfx = mu_left ? cfx - 16'd16 : cfx + 16'd16;    // slide 1 px a frame
                        cfy = cfy + cfvy;
                    end
                    fxp = cfx[15:4];
                    fyp = cfy >>> 4;
                    map_addr <= tile_at(mu_left ? fxp : fxp + 12'd15, fyp + 12'sd8);    // wall ahead
                    step <= 6'd23;
                end
            end
            6'd23: begin
                map_addr <= tile_at(fxp + 12'd2, fyp + 12'sd16);                    // floor, left
                step <= 6'd24;
            end
            6'd24: begin
                t1 <= map_rd;
                map_addr <= tile_at(fxp + 12'd13, fyp + 12'sd16);                   // floor, right
                step <= 6'd25;
            end
            6'd25: begin
                if (solid(t1)) begin                                                // wall: turn round
                    mu_left <= !mu_left;
                    cfx = mu_left ? cfx + 16'd16 : cfx - 16'd16;
                end
                t1 <= map_rd;
                step <= 6'd26;
            end
            6'd26: begin
                if (mu_st == 2'd2 && cfvy >= 0 && (solid(t1) || solid(map_rd))) begin
                    feet = fyp + 12'sd16;
                    fyp  = {feet[11:4], 4'd0} - 12'sd16;
                    cfy  = {fyp, 4'd0};
                    cfvy = 8'sd0;
                end
                fxp = cfx[15:4];
                fyp = cfy >>> 4;
                if (mu_st == 2'd2) begin
                    mu_x  <= cfx;
                    mu_y  <= cfy;
                    mu_vy <= cfvy;
                end
                hx = px[15:4];
                hy = py >>> 4;
                if (mu_st != 0 && (fyp > 12'sd240 || fxp + 12'd32 < cam_x)) begin
                    mu_st <= 2'd0;                                                  // lost
                end else if (mu_st != 0 && mode == M_PLAY && hx + 12'd11 > fxp + 12'd1 && hx < fxp + 12'd15 &&
                             hy + hh - 12'sd1 > fyp + 12'sd2 && hy < fyp + 12'sd16) begin
                    mu_st <= 2'd0;                                                  // eaten
                    add_score(24'h001000);
                    sfx <= SFX_POWER;
                    if (!big) begin
                        big    <= 1'b1;
                        py     <= py - 16'sd192;                                   // grow upwards
                        grow_t <= 6'd48;
                    end
                end
                step <= 6'd27;
            end
            6'd27: begin
                dyp  = mu_y >>> 4;
                mush <= {mu_st != 2'd0, F_MUSHROOM, dyp[9:0], mu_x[15:4]};
                step <= 6'd0;
            end

            default: step <= 6'd0;
        endcase
    end
endmodule


// Colour of screen pixel (x, y), 3 clocks later.
module plat_render (
    input  wire              clk,
    input  wire [9:0]        x,
    input  wire [9:0]        y,
    input  wire [2:0]        mode,
    input  wire [11:0]       cam_x,
    input  wire [11:0]       hero_x,
    input  wire signed [9:0] hero_y,
    input  wire [3:0]        hero_f,
    input  wire              hero_vis,
    input  wire              hero_big,
    input  wire [107:0]      foes,
    input  wire [26:0]       pop,
    input  wire [107:0]      debris,
    input  wire [26:0]       mush,
    input  wire [9:0]        mush_clip,
    input  wire [23:0]       score,
    input  wire [7:0]        coins,
    input  wire [11:0]       timer,
    input  wire [3:0]        lives,
    input  wire [3:0]        world,
    input  wire [7:0]        frames,
    output wire [11:0]       map_addr,
    input  wire [5:0]        map_rd,
    output reg  [23:0]       rgb = 24'd0
);
    `include "plat_params.vh"

    reg [3:0]  tiles_rom   [0:16383];               // 64 slots x 16 x 16
    reg [5:0]  slots_rom   [0:255];                 // {tile id, animation frame} -> slot
    reg [3:0]  sprites_rom [0:8191];                // 32 frames x 16 x 16
    reg [7:0]  font_rom    [0:511];                 // 64 glyphs x 8 rows
    reg [1:0]  logo_rom    [0:16383];               // LOGO_H rows of 256
    reg [21:0] rows_rom    [0:255];                 // {page, text row} -> {valid, column, length, offset}
    reg [6:0]  text_rom    [0:511];
    reg [23:0] palette_rom [0:63];
    initial begin
        $readmemh("plat_tiles.hex",   tiles_rom);
        $readmemh("plat_slots.hex",   slots_rom);
        $readmemh("plat_sprites.hex", sprites_rom);
        $readmemh("plat_font.hex",    font_rom);
        $readmemh("plat_logo.hex",    logo_rom);
        $readmemh("plat_rows.hex",    rows_rom);
        $readmemh("plat_text.hex",    text_rom);
        $readmemh("plat_palette.hex", palette_rom);
    end

    localparam [2:0] M_TITLE = 0, M_CARD = 1, M_PLAY = 2, M_DYING = 3, M_CLEAR = 4, M_GAMEOVER = 5, M_TIMEUP = 6;
    wire [2:0] page = mode == M_TITLE ? PG_TITLE : mode == M_CARD ? PG_CARD : mode == M_GAMEOVER ? PG_GAMEOVER :
                      mode == M_CLEAR ? PG_CLEAR : mode == M_TIMEUP ? PG_TIMEUP : PG_PLAY;
    wire       black = mode == M_CARD || mode == M_GAMEOVER || mode == M_TIMEUP;

    // ---------------------------------------------------------------- clock 0: addresses
    wire [8:0]  lx = x[9:1];
    wire [7:0]  ly = y[8:1];
    wire [11:0] wx = {3'b000, lx} + cam_x;              // position in the level
    assign map_addr = {ly[7:4], wx[11:4]};

    // Sprites: the hero on port A, the first other sprite covering the pixel on port B.
    function [26:0] slot(input [107:0] v, input [1:0] i);
        slot = v[27 * i +: 27];
    endfunction
    function covers(input [26:0] s, input [11:0] px, input [7:0] py);
        reg [11:0] dx;
        reg [9:0]  dy;
        begin
            dx     = px - s[11:0];
            dy     = {2'b00, py} - s[21:12];
            covers = s[26] && dx[11:4] == 0 && dy[9:4] == 0;
        end
    endfunction
    function [7:0] offset(input [26:0] s, input [11:0] px, input [7:0] py);
        reg [11:0] dx;
        reg [9:0]  dy;
        begin
            dx     = px - s[11:0];
            dy     = {2'b00, py} - s[21:12];
            offset = {dy[3:0], dx[3:0]};
        end
    endfunction

    // Big Nano is 32 tall: the top and bottom halves are consecutive frames from 16.
    wire [26:0] hero    = {hero_vis, hero_f, hero_y, hero_x};
    wire [9:0]  hero_dy = {2'b00, ly} - hero_y;
    wire        hero_in = hero_big ? hero_vis && (wx - hero_x) < 12'd16 && hero_dy[9:5] == 0 : covers(hero, wx, ly);
    wire [4:0]  hero_fr = hero_big ? {1'b1, hero_f[2:0], hero_dy[4]} : {1'b0, hero_f};
    wire        pop_in  = covers(pop, wx, ly);
    wire [3:0]  foe_in  = {covers(slot(foes, 3), wx, ly), covers(slot(foes, 2), wx, ly),
                           covers(slot(foes, 1), wx, ly), covers(slot(foes, 0), wx, ly)};
    wire [3:0]  deb_in  = {covers(slot(debris, 3), wx, ly), covers(slot(debris, 2), wx, ly),
                           covers(slot(debris, 1), wx, ly), covers(slot(debris, 0), wx, ly)};
    wire        mush_in = covers(mush, wx, ly) && {2'b00, ly} < mush_clip;     // hidden inside its block while rising
    wire [26:0] other   = pop_in ? pop : mush_in ? mush : foe_in[0] ? slot(foes, 0) : foe_in[1] ? slot(foes, 1) :
                          foe_in[2] ? slot(foes, 2) : foe_in[3] ? slot(foes, 3) :
                          deb_in[0] ? slot(debris, 0) : deb_in[1] ? slot(debris, 1) :
                          deb_in[2] ? slot(debris, 2) : slot(debris, 3);
    wire        other_in = pop_in || mush_in || foe_in != 0 || deb_in != 0;

    // Text: each page has at most one run of characters per 8-px row.
    wire [21:0] row_e = rows_rom[{page, ly[7:3]}];
    wire [5:0]  cx    = lx[8:3];
    wire [5:0]  rel   = cx - row_e[20:15];
    wire        text_in = row_e[21] && cx >= row_e[20:15] && rel < row_e[14:9];

    // Title logo.
    wire [8:0]  gx = lx - LOGO_X;
    wire [7:0]  gy = ly - LOGO_Y;
    wire        logo_in = mode == M_TITLE && lx >= LOGO_X && lx < LOGO_X + LOGO_W && ly >= LOGO_Y && ly < LOGO_Y + LOGO_H;

    // ---------------------------------------------------------------- clock 1: first lookups
    reg [3:0] spr_a1 = 0, spr_b1 = 0, tx1 = 0, ty1 = 0;
    reg       hero_in1 = 0, other_in1 = 0, text_in1 = 0, logo_in1 = 0, black1 = 0;
    reg [6:0] code1 = 0;
    reg [2:0] cgx1 = 0, cgy1 = 0;
    reg [1:0] logo1 = 0;

    always @(posedge clk) begin
        spr_a1    <= sprites_rom[{hero_fr, offset(hero, wx, ly)}];
        spr_b1    <= sprites_rom[{1'b0, other[25:22], offset(other, wx, ly)}];
        hero_in1  <= hero_in;
        other_in1 <= other_in;
        code1     <= text_rom[row_e[8:0] + {3'b000, rel}];
        text_in1  <= text_in;
        cgx1      <= lx[2:0];
        cgy1      <= ly[2:0];
        logo1     <= logo_rom[{gy[5:0], gx[7:0]}];
        logo_in1  <= logo_in;
        tx1       <= wx[3:0];
        ty1       <= ly[3:0];
        black1    <= black;
    end

    // ---------------------------------------------------------------- clock 2: tile pixel and glyph row
    // Dynamic text: score, coins, time, lives and world are filled in here.
    reg [5:0] glyph;
    always @(*) begin
        case (code1[5:0])
            C_SCORE5: glyph = C_DIGIT0 + score[23:20];
            C_SCORE4: glyph = C_DIGIT0 + score[19:16];
            C_SCORE3: glyph = C_DIGIT0 + score[15:12];
            C_SCORE2: glyph = C_DIGIT0 + score[11:8];
            C_SCORE1: glyph = C_DIGIT0 + score[7:4];
            C_SCORE0: glyph = C_DIGIT0 + score[3:0];
            C_COIN1:  glyph = C_DIGIT0 + coins[7:4];
            C_COIN0:  glyph = C_DIGIT0 + coins[3:0];
            C_TIME2:  glyph = C_DIGIT0 + timer[11:8];
            C_TIME1:  glyph = C_DIGIT0 + timer[7:4];
            C_TIME0:  glyph = C_DIGIT0 + timer[3:0];
            C_LIVES:  glyph = C_DIGIT0 + lives;
            C_WORLD:  glyph = C_DIGIT0 + world;
            default:  glyph = code1[5:0];
        endcase
    end

    wire [5:0] tile_slot = slots_rom[{map_rd, frames[4:3]}];

    reg [3:0] tile2 = 0, spr_a2 = 0, spr_b2 = 0;
    reg [7:0] font2 = 0;
    reg [2:0] cgx2 = 0;
    reg [1:0] logo2 = 0;
    reg       hero_in2 = 0, other_in2 = 0, text_in2 = 0, logo_in2 = 0, black2 = 0;

    always @(posedge clk) begin
        tile2     <= tiles_rom[{tile_slot, ty1, tx1}];
        font2     <= font_rom[{glyph, cgy1}];
        text_in2  <= text_in1 && !(code1[6] && frames[5]);  // bit 6: blinks
        cgx2      <= cgx1;
        spr_a2    <= spr_a1;    hero_in2  <= hero_in1;
        spr_b2    <= spr_b1;    other_in2 <= other_in1;
        logo2     <= logo1;     logo_in2  <= logo_in1;
        black2    <= black1;
    end

    // ---------------------------------------------------------------- clock 3: pick the colour
    reg [5:0] ci;
    always @(*) begin
        if (text_in2 && font2[3'd7 - cgx2])      ci = P_TEXT;
        else if (hero_in2 && spr_a2 != 0)        ci = P_SPRITE + spr_a2;
        else if (other_in2 && spr_b2 != 0)       ci = P_SPRITE + spr_b2;
        else if (logo_in2 && logo2 != 0)         ci = P_LOGO + logo2 - 1'b1;
        else if (black2)                         ci = P_BLACK;
        else                                     ci = P_TILE + tile2;
    end

    always @(posedge clk)
        rgb <= palette_rom[ci];
endmodule


// Sound effects: a few notes each, as a square wave on one pin.
module plat_sfx (
    input  wire       clk,          // 25.2 MHz
    input  wire       tick,         // once per frame
    input  wire [3:0] sfx,          // one-clock pulse starts an effect
    output reg        out = 1'b0
);
    // {half period in clocks, length in frames} of note n of effect e; length 0 ends it.
    function [21:0] note(input [3:0] e, input [1:0] n);
        case ({e, n})
            {4'd1, 2'd0}: note = {16'd21000, 6'd2};     // jump: a quick rising sweep
            {4'd1, 2'd1}: note = {16'd16800, 6'd2};
            {4'd1, 2'd2}: note = {16'd14000, 6'd3};
            {4'd2, 2'd0}: note = {16'd12753, 6'd4};     // coin
            {4'd2, 2'd1}: note = {16'd9553,  6'd14};
            {4'd3, 2'd0}: note = {16'd38182, 6'd3};     // stomp
            {4'd3, 2'd1}: note = {16'd57273, 6'd4};
            {4'd4, 2'd0}: note = {16'd63000, 6'd4};     // bump
            {4'd5, 2'd0}: note = {16'd16071, 6'd8};     // lose a life: falling notes
            {4'd5, 2'd1}: note = {16'd19120, 6'd8};
            {4'd5, 2'd2}: note = {16'd24092, 6'd8};
            {4'd5, 2'd3}: note = {16'd32143, 6'd20};
            {4'd6, 2'd0}: note = {16'd24092, 6'd7};     // course clear: rising arpeggio
            {4'd6, 2'd1}: note = {16'd19120, 6'd7};
            {4'd6, 2'd2}: note = {16'd16071, 6'd7};
            {4'd6, 2'd3}: note = {16'd12034, 6'd24};
            {4'd7, 2'd0}: note = {16'd9553,  6'd5};     // extra life
            {4'd7, 2'd1}: note = {16'd8036,  6'd5};
            {4'd7, 2'd2}: note = {16'd6020,  6'd5};
            {4'd7, 2'd3}: note = {16'd7159,  6'd10};
            {4'd9, 2'd0}: note = {16'd31500, 6'd3};     // mushroom appears
            {4'd9, 2'd1}: note = {16'd25200, 6'd3};
            {4'd9, 2'd2}: note = {16'd21000, 6'd4};
            {4'd10, 2'd0}: note = {16'd24092, 6'd5};    // power-up: a rising arpeggio
            {4'd10, 2'd1}: note = {16'd19120, 6'd5};
            {4'd10, 2'd2}: note = {16'd16071, 6'd5};
            {4'd10, 2'd3}: note = {16'd12034, 6'd14};
            {4'd11, 2'd0}: note = {16'd16071, 6'd5};    // shrink: falling
            {4'd11, 2'd1}: note = {16'd21465, 6'd5};
            {4'd11, 2'd2}: note = {16'd32143, 6'd10};
            {4'd8, 2'd0}: note = {16'd50400, 6'd2};     // brick breaking: a rough crunch
            {4'd8, 2'd1}: note = {16'd63000, 6'd2};
            {4'd8, 2'd2}: note = {16'd42000, 6'd2};
            {4'd8, 2'd3}: note = {16'd63000, 6'd3};
            default:      note = 22'd0;
        endcase
    endfunction

    reg [3:0]  e = 4'd0;
    reg [1:0]  n = 2'd0;
    reg [5:0]  left = 6'd0;
    reg [15:0] cnt = 16'd0;
    reg        playing = 1'b0;
    wire [21:0] cur = note(e, n);

    always @(posedge clk) begin
        if (sfx != 4'd0) begin
            e <= sfx; n <= 2'd0; left <= note(sfx, 2'd0); playing <= 1'b1; cnt <= 16'd0;
        end else if (playing) begin
            if (tick) begin
                if (left <= 6'd1) begin
                    if (n == 2'd3 || note(e, n + 1'b1) == 22'd0) playing <= 1'b0;
                    else begin n <= n + 1'b1; left <= note(e, n + 1'b1); end
                end else begin
                    left <= left - 1'b1;
                end
            end
            if (cnt >= cur[21:6]) begin cnt <= 16'd0; out <= ~out; end
            else cnt <= cnt + 1'b1;
        end else begin
            out <= 1'b0;
        end
    end
endmodule
