#!/usr/bin/env python3
"""Colour tables for pong.v (all entries 24-bit rrggbb for $readmemh).

  pong_solid.hex  64  opaque colours: ball, paddles, digits, walls, text, rainbow
  pong_add.hex    32  colours added on top: sparks, fire trail, lake reflections, net
  pong_glow.hex  256  glow            [source][variant][level 0..15]: ball [heat], paddle
                      [side, just hit], wall
  pong_flash.hex  32  goal flash       [side][level 0..15]
  pong_grid.hex   64  neon theme background [grid line][band 0..31]
  pong_div6.hex  128  n -> {n / 6, n % 6}, to find the character and column in a text line
  pong_pal.vh         palette indices and phosphor tints for pong.v

Glows fall off with the square of the distance, so the tables hold colour * (g / max)^2.
"""
import colorsys

CYAN, MAGENTA = (25, 230, 255), (255, 46, 200)          # player (left), computer (right)
BALL_CORE = [(200, 248, 255), (255, 255, 255), (255, 244, 170), (255, 205, 170)]
BALL_GLOW = [(0, 200, 255), (160, 190, 255), (255, 185, 40), (255, 60, 30)]   # cool .. red-hot
WALL = (61, 123, 255)
FIRE = [(255, 255, 255, 0.9), (255, 225, 130, 0.75), (255, 165, 60, 0.6), (255, 105, 50, 0.5),
        (235, 60, 90, 0.4), (175, 50, 140, 0.3), (115, 40, 150, 0.22), (60, 30, 120, 0.15)]
SPARK = [(0, 0, 0), (120, 30, 60), (190, 50, 70), (240, 90, 60), (255, 150, 60),
         (255, 205, 90), (255, 240, 160), (255, 255, 235)]
TINTS = {"GREEN": (70, 255, 120), "AMBER": (255, 170, 40)}

# Indices into pong_solid.hex / pong_add.hex, exported to pong_pal.vh.
SOL = {"NONE": 0, "BALL": 1, "LPAD": 5, "RPAD": 6, "LPAD_HIT": 7, "RPAD_HIT": 8, "LDIG": 9,
       "RDIG": 10, "WALL": 12, "PRESS": 13, "OVER": 14, "HUE": 32}
ADD = {"NONE": 0, "BALL_REFL": 1, "LPAD_REFL": 5, "RPAD_REFL": 6, "NET": 7, "TRAIL": 8, "SPARK": 16}


def scale(c, k):
    return tuple(min(255, round(v * k)) for v in c)


def mix(a, b, t):
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b))


def solid():
    t = [(0, 0, 0)] * 64
    for i, c in enumerate(BALL_CORE):
        t[SOL["BALL"] + i] = c
    t[SOL["LPAD"]], t[SOL["RPAD"]] = CYAN, MAGENTA
    t[SOL["LPAD_HIT"]], t[SOL["RPAD_HIT"]] = mix(CYAN, (255, 255, 255), 0.75), mix(MAGENTA, (255, 255, 255), 0.75)
    t[SOL["LDIG"]], t[SOL["RDIG"]] = CYAN, MAGENTA
    t[SOL["WALL"]] = WALL
    t[SOL["PRESS"]] = (255, 228, 92)
    t[SOL["OVER"]] = (255, 59, 92)
    for h in range(32):
        r, g, b = colorsys.hsv_to_rgb(h / 32, 0.8, 1.0)
        t[SOL["HUE"] + h] = (round(r * 255), round(g * 255), round(b * 255))
    return t


def additive():
    t = [(0, 0, 0)] * 32
    for i, c in enumerate(BALL_GLOW):
        t[ADD["BALL_REFL"] + i] = scale(mix(c, (255, 255, 255), 0.3), 0.45)
    t[ADD["LPAD_REFL"]], t[ADD["RPAD_REFL"]] = scale(CYAN, 0.35), scale(MAGENTA, 0.35)
    t[ADD["NET"]] = (70, 60, 110)
    for age, (r, g, b, k) in enumerate(FIRE):
        t[ADD["TRAIL"] + age] = scale((r, g, b), k)
    for lvl, c in enumerate(SPARK):
        t[ADD["SPARK"] + lvl] = c
    return t


def falloff(color, levels, strength):
    return [scale(color, strength * (min(g, levels) / levels) ** 2) for g in range(16)]


def glow():
    ball = [c for col in BALL_GLOW for c in falloff(col, 14, 0.85)]
    paddle = []
    for col in (CYAN, MAGENTA):
        paddle += falloff(col, 12, 0.6)                                       # normal
        paddle += falloff(mix(col, (255, 255, 255), 0.35), 12, 1.0)           # just hit
    wall = falloff(WALL, 8, 0.55) + [(0, 0, 0)] * 48
    return ball + paddle + wall + [(0, 0, 0)] * 64


def grid():
    top, mid, bottom = (8, 6, 30), (22, 8, 50), (44, 8, 56)
    bands = [mix(top, mid, b / 15) if b < 15 else mix(mid, bottom, (b - 15) / 16) for b in range(32)]
    line = (40, 50, 130)
    return bands + [tuple(min(255, x + y) for x, y in zip(c, line)) for c in bands]


def goal_flash():
    return [scale(col, 0.4 * lvl / 15) for col in (CYAN, MAGENTA) for lvl in range(16)]


def write_hex(name, rgbs):
    with open(name, "w") as f:
        f.write("\n".join(f"{r:02x}{g:02x}{b:02x}" for r, g, b in rgbs) + "\n")


def main():
    write_hex("pong_solid.hex", solid())
    write_hex("pong_add.hex", additive())
    write_hex("pong_glow.hex", glow())
    write_hex("pong_flash.hex", goal_flash())
    write_hex("pong_grid.hex", grid())
    with open("pong_div6.hex", "w") as f:
        f.write("\n".join(f"{((n // 6) << 3) | (n % 6):02x}" for n in range(128)) + "\n")
    lines = ["// Generated by pong_gen.py - do not edit."]
    lines += [f"localparam [5:0] SOL_{k} = {v};" for k, v in SOL.items()]
    lines += [f"localparam [4:0] ADD_{k} = {v};" for k, v in ADD.items()]
    lines += [f"localparam [23:0] TINT_{k} = 24'h{r:02x}{g:02x}{b:02x};" for k, (r, g, b) in TINTS.items()]
    with open("pong_pal.vh", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote pong_*.hex and pong_pal.vh")


if __name__ == "__main__":
    main()
